### ISSUE TITLE
Unable to use global variables

### ISSUE THREAD

**Issue by parsoyaarihant** [p5py/p5#107]
Unable to use global variable inside `draw()` function

**To Reproduce**
```python
from p5 import *

y = 0

def setup():
	size(640, 360)
	stroke(255)

def draw():
	background(0)
	y = y - 1
	if y < 0:
		y = height

	line((0, y), (width, y))


if __name__ == '__main__':
    run()
```
**Output**
```python
WARNING: Traceback (most recent call last):
  File "test.py", line 26, in <module>
    run()
  File "/Users/arihantparsoya/Documents/p5/p5/sketch/userspace.py", line 146, in run
    app.run()
  File "/Users/arihantparsoya/anaconda3/lib/python3.7/site-packages/vispy-0.5.3-py3.7.egg/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/Users/arihantparsoya/anaconda3/lib/python3.7/site-packages/vispy-0.5.3-py3.7.egg/vispy/app/application.py", line 142, in run
    return self._backend._vispy_run()
  File "/Users/arihantparsoya/anaconda3/lib/python3.7/site-packages/vispy-0.5.3-py3.7.egg/vispy/app/backends/_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "/Users/arihantparsoya/anaconda3/lib/python3.7/site-packages/vispy-0.5.3-py3.7.egg/vispy/app/backends/_glfw.py", line 183, in _vispy_process_events
    timer._tick()
  File "/Users/arihantparsoya/anaconda3/lib/python3.7/site-packages/vispy-0.5.3-py3.7.egg/vispy/app/backends/_glfw.py", line 516, in _tick
    self._vispy_timer._timeout()
  File "/Users/arihantparsoya/anaconda3/lib/python3.7/site-packages/vispy-0.5.3-py3.7.egg/vispy/app/timer.py", line 168, in _timeout
    count=self.iter_count)
  File "/Users/arihantparsoya/anaconda3/lib/python3.7/site-packages/vispy-0.5.3-py3.7.egg/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/arihantparsoya/anaconda3/lib/python3.7/site-packages/vispy-0.5.3-py3.7.egg/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/arihantparsoya/anaconda3/lib/python3.7/site-packages/vispy-0.5.3-py3.7.egg/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/arihantparsoya/Documents/p5/p5/sketch/base.py", line 150, in on_timer
    self.draw_method()
  File "test.py", line 18, in draw
    y = y - 1
UnboundLocalError: local variable 'y' referenced before assignment
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x108468898>> for Event
```
**System information:**
 - Python version: 3.7
 - Operating system: MacOS Mojave

**Comment by parsoyaarihant** [comment]
This issue is caused because Python treats the line `y = y - 1`  as an assignment of a local variable. Using ` global` fixes the issue:

``` python
from p5 import *

y = 0

def setup():
	size(640, 360)
	stroke(255)

def draw():
	background(0)
	
	global y
	y = y - 1
	if y < 0:
		y = height

	line((0, y), (width, y))


if __name__ == '__main__':
    run()

```
