### ISSUE TITLE
No module named 'OpenGL'

### ISSUE THREAD

**Issue by kylemcdonald** [p5py/p5#11]
**Test script:**

```python
from p5 import *
```

**Expected behavior:**

Import p5py

**Actual behavior**

Error.

**Errors produced (if any):**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kyle/Library/Python/3.6/lib/python/site-packages/p5/__init__.py", line 19, in <module>
    from .sketch import *
  File "/Users/kyle/Library/Python/3.6/lib/python/site-packages/p5/sketch/__init__.py", line 19, in <module>
    from .base import *
  File "/Users/kyle/Library/Python/3.6/lib/python/site-packages/p5/sketch/base.py", line 29, in <module>
    from ..opengl import renderer
  File "/Users/kyle/Library/Python/3.6/lib/python/site-packages/p5/opengl/__init__.py", line 19, in <module>
    from .renderer import *
  File "/Users/kyle/Library/Python/3.6/lib/python/site-packages/p5/opengl/renderer.py", line 26, in <module>
    from . import gl
  File "/Users/kyle/Library/Python/3.6/lib/python/site-packages/p5/opengl/gl.py", line 14, in <module>
    import OpenGL
ModuleNotFoundError: No module named 'OpenGL'
```

**p5 version:**

p5 (0.3.0a1)

**Python version:**

Python 3.6.2

**Operating System:** 

macOS 10.12.6

**Comment by kylemcdonald** [comment]
This was fixed for me by running:

```
$ pip install PyOpenGL PyOpenGL_accelerate
```

**Comment by abhikpal** [comment]
Ahhh.. yes! PyOpenGL was missing as a dependency in `setup.py` I'm just about to push a fix.

**Comment by abhikpal** [comment]
I've pushed a fix! Thanks a lot for pointing this out!
