### ISSUE TITLE
TypeError: type object argument after * must be an iterable, not int

### ISSUE THREAD

**Issue by emme1444** [p5py/p5#117]
**Describe the bug**
I tried running this piece of code:
```python
from p5 import *

def setup():
    background(255)

def draw():
    background(255)

    no_stroke()
    fill(0)
    ellipse(mouse_x, mouse_y, 20)

run()
```

and it spits back this error. 

```
WARNING: Traceback (most recent call last):
  File "main.py", line 16, in <module>
    run()
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/p5/sketch/userspace.py", line 146, in run
    app.run()
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/vispy/app/application.py", line 152, in run
    return self._backend._vispy_run()
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/vispy/app/backends/_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/vispy/app/backends/_glfw.py", line 183, in _vispy_process_events
    timer._tick()
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/vispy/app/backends/_glfw.py", line 516, in _tick
    self._vispy_timer._timeout()
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/vispy/app/timer.py", line 168, in _timeout
    count=self.iter_count)
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/p5/sketch/base.py", line 150, in on_timer
    self.draw_method()
  File "main.py", line 13, in draw
    ellipse(mouse_x, mouse_y, 20)
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/p5/core/primitives.py", line 527, in ellipse
    return arc(coordinate, width, height, 0, math.pi * 2, 'CHORD', mode)
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/p5/core/primitives.py", line 75, in wrapped
    s = func(*args, **kwargs)
  File "/home/emil/.local/share/virtualenvs/digit-recognition-Df8tzTvE/lib/python3.6/site-packages/p5/core/primitives.py", line 479, in arc
    center = Point(*coordinate)
TypeError: type object argument after * must be an iterable, not int
```

I can read what it says, but I have a hard time understanding it. Plus it's somewhere in the source code, and I don't know my way round the codebase. 

I don't know if it's hardware based or just some typo. 

Maybe it's because I use `pipenv`. Worth noting. 

**To Reproduce**
`main.py`:
```python
from p5 import *

def setup():
    background(255)

def draw():
    background(255)

    no_stroke()
    fill(0)
    ellipse(mouse_x, mouse_y, 20)

run()
```

```bash
$ pipenv run python main.py
```
or
```bash
$ python main.py
```

**Expected behavior**
It should display a white canvas with a circle following the mouse position. 

**Current behavior**
Instead it just displays a white background without any circle. 

**System information:**
 - p5 release (version number or latest commit): 0.5.0
 - Python version: 3.6.8
 - Operating system: Ubuntu 18.04.2
 - pipenv: 2018.11.26

**Comment by emme1444** [comment]
I finally read the documentation, and came to the conclusion that this python version of p5, for some freaking reason, takes a tuple as coordinates instead of `x` and `y` arguments respectively. 

Sorry!

**Comment by jeremydouglass** [comment]
Reference for convenience:

> ### p5 for Processing users
> ...
> #### Shapes, etc.
>One of the major differences between the Processing and the p5 API is the way coördinate points are handled. With the exception of the point() functions, all drawing functions that allow the user to pass in coordinates use tuples.

https://p5.readthedocs.io/en/latest/guides/for-processing-users.html#shapes-etc
