### ISSUE TITLE
Python 3.8 : Vispy - RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by ThatIsAPseudo** [p5py/p5#136]
I don't know if it is relevant to issue this error since this library may not be 3.8-ready, yet the [documentation](https://p5.readthedocs.io/en/latest/install.html) says :

> If the reported version is greater than 3.0, you’re good to proceed

Which seems to be false.

**System information:**
 - p5 release : latest commit https://github.com/p5py/p5/commit/2e8de54467883e38d0cf0e61e3106e228845cb99
 - Python version: 3.8 (with miniconda)
 - Operating system: macOS Mojave 10.14.6

**Describe the bug**
Running the example sketch results in the following :
```python
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    run()
  File "/Users/Username/miniconda3/envs/p5js/lib/python3.8/site-packages/p5/sketch/userspace.py", line 149, in run
    p5.sketch = Sketch(setup_method, draw_method, handlers, frame_rate)
  File "/Users/Username/miniconda3/envs/p5js/lib/python3.8/site-packages/p5/sketch/base.py", line 60, in __init__
    app.Canvas.__init__(
  File "/Users/Username/miniconda3/envs/p5js/lib/python3.8/site-packages/vispy/app/canvas.py", line 194, in __init__
    self._set_keys(keys)
  File "/Users/Username/miniconda3/envs/p5js/lib/python3.8/site-packages/vispy/app/canvas.py", line 249, in _set_keys
    for key, val in keys.items():
RuntimeError: dictionary keys changed during iteration
```

**How to solve**
I simply downgraded Python to version 3.7.5 with `conda install python=3.7` and now everything works as intended.

**To Reproduce**
Run the example sketch with Python 3.8

**Expected behavior**
The sketch was supposed to run without error.

**Additional context**
- I bypassed the content in the functions with `pass`, but got the same error.
- Conda env :
```shell
$ conda list
# packages in environment at /Users/Username/miniconda3/envs/p5js_3.8:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.10.16                    0
certifi                   2019.9.11                py38_0
freetype-py               2.1.0.post1              pypi_0    pypi
glfw                      1.8.4                    pypi_0    pypi
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
ncurses                   6.1                  h0a44026_1
numpy                     1.17.3                   pypi_0    pypi
openssl                   1.1.1d               h1de35cc_3
p5                        0.6.0                    pypi_0    pypi
pillow                    6.2.1                    pypi_0    pypi
pip                       19.3.1                   py38_0
python                    3.8.0                h359304d_1
readline                  7.0                  h1de35cc_5
setuptools                41.6.0                   py38_0
sqlite                    3.30.1               ha441bb4_0
tk                        8.6.8                ha441bb4_0
triangle                  20190115.3               pypi_0    pypi
vispy                     0.6.1                    pypi_0    pypi
wheel                     0.33.6                   py38_0
xz                        5.2.4                h1de35cc_4
zlib                      1.2.11               h1de35cc_3
```

**Comment by jeremydouglass** [comment]
This is a python 3.8 incompatibility in vispy -- it has been fixed in https://github.com/vispy/vispy/issues/1729 and released in 0.6.2, so updating should resolve the issue.

https://github.com/vispy/vispy/releases/tag/v0.6.2
