### ISSUE TITLE
AttributeError: 'Geometry' object has no attribute 'children'

### ISSUE THREAD

**Issue by bailefunk** [p5py/p5#141]
``` python
from p5 import *

W = 1280
H = 720
BG_COLOR = 12

def setup():
    size(W, H)    
    background(BG_COLOR)

def draw():
    box(100, 100, 5)

run(mode='P3D')
```

```
WARNING: Traceback (most recent call last):
  File "mole.py", line 21, in <module>
    run(mode='P3D')
  File "D:\conda_envs\chi2019\lib\site-packages\p5\sketch\userspace.py", line 159, in run
    app.run()
  File "D:\conda_envs\chi2019\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "D:\conda_envs\chi2019\lib\site-packages\vispy\app\application.py", line 152, in run
    return self._backend._vispy_run()
  File "D:\conda_envs\chi2019\lib\site-packages\vispy\app\backends\_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "D:\conda_envs\chi2019\lib\site-packages\vispy\app\backends\_glfw.py", line 183, in _vispy_process_events
    timer._tick()
  File "D:\conda_envs\chi2019\lib\site-packages\vispy\app\backends\_glfw.py", line 516, in _tick
    self._vispy_timer._timeout()
  File "D:\conda_envs\chi2019\lib\site-packages\vispy\app\timer.py", line 168, in _timeout
    count=self.iter_count)
  File "D:\conda_envs\chi2019\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "D:\conda_envs\chi2019\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "D:\conda_envs\chi2019\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "D:\conda_envs\chi2019\lib\site-packages\p5\sketch\base.py", line 104, in on_timer
    self.draw_method()
  File "mole.py", line 17, in draw
    box(100, 100, 5)
  File "D:\conda_envs\chi2019\lib\site-packages\p5\core\primitives.py", line 69, in wrapped
    draw_shape(s)
  File "D:\conda_envs\chi2019\lib\site-packages\p5\core\primitives.py", line 582, in draw_shape
AttributeError: 'Geometry' object has no attribute 'children'
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x269db1c9288>> for Event
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x269db1c9288>> repeat 2
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x269db1c9288>> repeat 8
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x269db1c9288>> repeat 16
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x269db1c9288>> repeat 32
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x269db1c9288>> repeat 64
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x269db1c9288>> repeat 128
```

**System information:**
 - p5 release (version number or latest commit): p5==0.6.0
 - Python version: 3.7.5
 - Operating system: Windows 10

**Comment by ziyaointl** [comment]
I have encountered this issue too. Seems to appear whenever a 3D primitive is initialized.

**Comment by parsoyaarihant** [comment]
This bug has been fixed in the latest commit: https://github.com/p5py/p5/commit/56fd90d05a561c0b7b8bacacad0d300f21c2f268
