### ISSUE TITLE
having problem with the tutorial (Interactivity)

### ISSUE THREAD

**Issue by lil6mon** [p5py/p5#165]
**Describe the bug**
In the mouse event tutorial, the programm to test mouse_mouved and mouse_dragged doesn't work

**To Reproduce**
it's probably me but it is the exact same code

**Expected behavior**
to the circle to follow the mouse (they don't)

**System information:**
 - p5 release (version number or latest commit):
 - Python version: 3.8
 - Operating system: widnow 64bit

**Additional context**
i think it's about the mouse_mouved() function because the moveX stay on 0 while the mouse_x is changed

**Comment by lil6mon** [comment]
I still have issue with it, to solve the first, I put the variable in the draw / mouse_moved function in global but I have the feeling it's not how i have to do it...
Now I try something new and i get this long error message : 
WARNING: Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 361, in main
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 203, in run_file
    runpy.run_path(options.target, run_name="__main__")
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Simon\source\repos\Farm_IA_V1\Field.py", line 21, in <module>
    run()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\p5\sketch\userspace.py", line 159, in run
    app.run()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\vispy\app\application.py", line 152, in run
    return self._backend._vispy_run()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\vispy\app\backends\_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\vispy\app\backends\_glfw.py", line 183, in _vispy_process_events
    timer._tick()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\vispy\app\backends\_glfw.py", line 516, in _tick
    self._vispy_timer._timeout()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\vispy\app\timer.py", line 163, in _timeout
    self.events.timeout(
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\vispy\util\event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python38\lib\site-packages\p5\sketch\base.py", line 104, in on_timer
    self.draw_method()
  File "C:\Users\Simon\source\repos\Farm_IA_V1\Field.py", line 17, in draw
    animal.show()
  File "C:\Users\Simon\source\repos\Farm_IA_V1\Animals.py", line 10, in show
    circle(self.position, 5)
AttributeError: 'Animal' object has no attribute 'position'
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x1a7a2909370>> for Event
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x1a7a2909370>> repeat 2
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x1a7a2909370>> repeat 4
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x1a7a2909370>> repeat 8
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x1a7a2909370>> repeat 16
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x1a7a2909370>> repeat 32
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x1a7a2909370>> repeat 64

I'm starting on p5 if someone can help me

**Comment by parsoyaarihant** [comment]
@lil6mon , use this code instead:

```python
from p5 import *

dragX, dragY, moveX, moveY = (0, 0, 0, 0)

def setup():
	size(100, 100)
	no_stroke()

def draw():
	background(204)
	fill(0)

	ellipse((dragX, dragY), 33, 33) # Black circle
	fill(153)
	ellipse((moveX, moveY), 33, 33) # Gray circle

def mouse_moved():
	global moveX, moveY
	moveX = mouse_x
	moveY = mouse_y

def mouse_dragged():
	global dragX, dragY
	dragX = mouse_x
	dragY = mouse_y

if __name__ == '__main__':
	run()
```
