### ISSUE TITLE
Point shape causing concatenate error

### ISSUE THREAD

**Issue by MrFifths7** [p5py/p5#238]
**Describe the bug**
"Point" shape does not draw and causes concatenate error.

**To Reproduce**
Simply try and draw a point shape.

from p5 import *

def setup():
    size(640, 360)

def draw():
    background(255)
    point(width/2, height/2)

if __name__ == "__main__":
    run()

**Expected behavior**
Draw a point at center of window. When replaced with "circle" shape, it works.

**Error**
  File "c:\Users\Ian\anaconda3\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x19879a87e48>> for Event
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x19879a87e48>> repeat 2

**System information:**
 - p5 release (version number or latest commit): 0.7.0
 - Python version: 3.7.6 64-bit Anaconda
 - Operating system: Windows 10

**Additional context**

**Comment by MrFifths7** [comment]
The whole error is:

 

(base) C:\Users\Ian>c:/Users/Ian/anaconda3/python.exe "d:/Google Drive/Personal/Programming/The Nature of Code/0 - Introduction/Point bug report.py"

WARNING: Traceback (most recent call last):

  File "d:/Google Drive/Personal/Programming/The Nature of Code/0 - Introduction/Point bug report.py", line 11, in <module>

    run()

  File "c:\Users\Ian\anaconda3\lib\site-packages\p5\sketch\userspace.py", line 166, in run

    app.run()

  File "c:\Users\Ian\anaconda3\lib\site-packages\vispy\app\_default_app.py", line 62, in run

    return default_app.run()

  File "c:\Users\Ian\anaconda3\lib\site-packages\vispy\app\application.py", line 152, in run

    return self._backend._vispy_run()

  File "c:\Users\Ian\anaconda3\lib\site-packages\vispy\app\backends\_glfw.py", line 194, in _vispy_run

    self._vispy_process_events()

  File "c:\Users\Ian\anaconda3\lib\site-packages\vispy\app\backends\_glfw.py", line 183, in _vispy_process_events

    timer._tick()

  File "c:\Users\Ian\anaconda3\lib\site-packages\vispy\app\backends\_glfw.py", line 516, in _tick

    self._vispy_timer._timeout()

  File "c:\Users\Ian\anaconda3\lib\site-packages\vispy\app\timer.py", line 168, in _timeout

    count=self.iter_count)

  File "c:\Users\Ian\anaconda3\lib\site-packages\vispy\util\event.py", line 455, in __call__

    self._invoke_callback(cb, event)

  File "c:\Users\Ian\anaconda3\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback

    self, cb_event=(cb, event))

  << caught exception here: >>

  File "c:\Users\Ian\anaconda3\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback

    cb(event)

  File "c:\Users\Ian\anaconda3\lib\site-packages\p5\sketch\base.py", line 110, in on_timer

    self.draw_method()

  File "d:/Google Drive/Personal/Programming/The Nature of Code/0 - Introduction/Point bug report.py", line 8, in draw

    point(width/2, height/2)

  File "c:\Users\Ian\anaconda3\lib\site-packages\p5\core\primitives.py", line 71, in wrapped

    draw_shape(s)

  File "c:\Users\Ian\anaconda3\lib\site-packages\p5\core\primitives.py", line 548, in draw_shape

    p5.renderer.render(shape)

  File "c:\Users\Ian\anaconda3\lib\site-packages\p5\sketch\renderer2d.py", line 158, in render

    obj_list = get_render_primitives(shape)

  File "c:\Users\Ian\anaconda3\lib\site-packages\p5\sketch\openglrenderer.py", line 193, in get_render_primitives

    render_primitives.extend(_get_borders(shape))

  File "c:\Users\Ian\anaconda3\lib\site-packages\p5\sketch\openglrenderer.py", line 133, in _get_borders

    render_primitives.append(_get_line_from_verts(shape.vertices))

  File "c:\Users\Ian\anaconda3\lib\site-packages\p5\sketch\openglrenderer.py", line 37, in _get_line_from_verts

    return _get_line_from_indices(vertices, np.arange(n_vert - 1, dtype=np.uint32), np.arange(1, n_vert, dtype=np.uint32))

  File "c:\Users\Ian\anaconda3\lib\site-packages\p5\sketch\openglrenderer.py", line 55, in _get_line_from_indices

    np.hstack((np.vstack(start), np.vstack(end)))]

  File "<__array_function__ internals>", line 6, in vstack

  File "c:\Users\Ian\anaconda3\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack

    return _nx.concatenate(arrs, 0)

  File "<__array_function__ internals>", line 6, in concatenate

ValueError: need at least one array to concatenate

ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x152df197f48>> for Event

ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x152df197f48>> repeat 2

ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x152df197f48>> repeat 4

ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x152df197f48>> repeat 8

ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x152df197f48>> repeat 16

ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x152df197f48>> repeat 32

ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x152df197f48>> repeat 64

ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x152df197f48>> repeat 128
