### ISSUE TITLE
Could not import backend "Glfw" on Ubuntu 20.4

### ISSUE THREAD

**Issue by H1tman1978** [p5py/p5#275]
**Describe the bug**
Similar issue as Issue #76. Generates following error:
RuntimeError: Could not import backend "Glfw":
GLFW library not found

However Glfw was successfully installed:
![image](https://user-images.githubusercontent.com/35072659/92984509-2e635e00-f470-11ea-8c23-ec4359dbcbf0.png)

**To Reproduce**
code from main.py:
`
from p5 import *
import numpy as np
from boid import Boid

width = 1000
height = 1000

def setup():
    size(width, height)

def draw():
    background(30, 30, 47)

run(draw, setup)
`

**Expected behavior**
Well I was hoping that it would draw a window with a background as defined in the code. Was also hoping to win the lottery, but what are you going to do ;)

**Traceback**
Traceback (most recent call last):
  File "/home/tony/PycharmProjects/boidAlgorithm/main.py", line 1, in <module>
    from p5 import *
  File "/home/tony/PycharmProjects/boidAlgorithm/venv/lib/python3.8/site-packages/p5/__init__.py", line 19, in <module>
    from .sketch import *
  File "/home/tony/PycharmProjects/boidAlgorithm/venv/lib/python3.8/site-packages/p5/sketch/__init__.py", line 19, in <module>
    vispy.use('glfw')
  File "/home/tony/PycharmProjects/boidAlgorithm/venv/lib/python3.8/site-packages/vispy/util/wrappers.py", line 97, in use
    use_app(app)
  File "/home/tony/PycharmProjects/boidAlgorithm/venv/lib/python3.8/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/tony/PycharmProjects/boidAlgorithm/venv/lib/python3.8/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/tony/PycharmProjects/boidAlgorithm/venv/lib/python3.8/site-packages/vispy/app/application.py", line 235, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Glfw":
GLFW library not found

**System information:**
 - p5 release (version number or latest commit): 0.7.1
 - Python version: 3.8.2
 - Operating system: Ubuntu 20.04.1 LTS

**Additional context**
Working on an implementation of the Boid Algorithm. Not sure how this would be helpful, but that's the only additional context I have.

**Comment by ziyaointl** [comment]
I think you may need to manually install glfw
```bash
sudo apt-get install libglfw3-dev
```
Let me know if it works :)

**Comment by tushar5526** [comment]
I had trouble installing `libglfw3-dev` if that didn't work, try this
```
sudo apt-get install python-opengl libglfw3 -y
```

**Comment by H1tman1978** [comment]
> I think you may need to manually install glfw
> 
> ```shell
> sudo apt-get install libglfw3-dev
> ```
> 
> Let me know if it works :)

This worked...thanks!
