### ISSUE TITLE
Is there a way to print Chinese characters with text()?

### ISSUE THREAD

**Issue by WumingUmou** [p5py/p5#290]
I'm trying to display some Chinese characters with `text()`. 
But I got an error there. It seems that this error was related to the latin-1 codec. 
Is there a good way to show Chinese characters in P5py or is there a place I can change the decoder being used to utf-8?

**OS:** WIndows10
**Python version:** 3.7
**P5py version:** 0.7.1

*Source Code:*
```
from p5 import *

def setup():
    size(800, 600)

def draw():

    background(0, 5, 0)
    text("中文", 0,0)

if __name__ == "__main__":
    run()

```

*Error Message:*
```
C:\Users\Wumin\Anaconda3\envs\P5\python.exe C:/Users/Wumin/OneDrive/P5Py/Test_Canvas/main.py
WARNING: Traceback (most recent call last):
  File "C:/Users/Wumin/OneDrive/P5Py/Test_Canvas/main.py", line 20, in <module>
    run()
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\p5\sketch\userspace.py", line 166, in run
    app.run()
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\vispy\app\application.py", line 152, in run
    return self._backend._vispy_run()
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\vispy\app\backends\_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\vispy\app\backends\_glfw.py", line 183, in _vispy_process_events
    timer._tick()
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\vispy\app\backends\_glfw.py", line 516, in _tick
    self._vispy_timer._timeout()
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\vispy\app\timer.py", line 168, in _timeout
    count=self.iter_count)
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\p5\sketch\base.py", line 110, in on_timer
    self.draw_method()
  File "C:/Users/Wumin/OneDrive/P5Py/Test_Canvas/main.py", line 16, in draw
    text("中文", 0,0)
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\p5\core\font.py", line 119, in text
    size = _font_family.getsize(text_string)
  File "C:\Users\Wumin\Anaconda3\envs\P5\lib\site-packages\PIL\ImageFont.py", line 128, in getsize
    return self.font.getsize(text)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
```

**Comment by ReneTC** [comment]
Probably not the solution you are looking for, but you can download a custom Chinese font package and use that. 

```
from p5 import *

def setup():
    size(640, 360)
    no_stroke()
    background(204)

def draw():
    #load font
    font = create_font("path/to/font.ttf",size=100)

    #set font for p5
    text_font(font)

    #write some text
    text("symbols", 0,0)

run()
```

of course you would need to find out which symbols corresponds to some utf-8 input

**Comment by WumingUmou** [comment]
This works just I expected now. Thanks for that.
