### ISSUE TITLE
ERROR: Invoking <bound method Sketch.on_resize of <Sketch (Glfw) at 0x7f1eabc1c220>> for ResizeEvent

### ISSUE THREAD

**Issue by lipol** [p5py/p5#354]
**Describe the bug**
Every example code ends up with this warning and error. Same results on Ubuntu and Windows machines. 
```
WARNING: Traceback (most recent call last):
  File "main.py", line 21, in <module>
    run()
  File "/home/user/.local/lib/python3.8/site-packages/p5/sketch/userspace.py", line 155, in run
    p5.sketch = Sketch(setup_method, draw_method, handlers, frame_rate)
  File "/home/user/.local/lib/python3.8/site-packages/p5/sketch/base.py", line 60, in __init__
    app.Canvas.__init__(
  File "/home/user/.local/lib/python3.8/site-packages/vispy/app/canvas.py", line 211, in __init__
    self.create_native()
  File "/home/user/.local/lib/python3.8/site-packages/vispy/app/canvas.py", line 228, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/vispy/app/backends/_glfw.py", line 298, in __init__
    self._on_resize(self._id, size[0], size[1])
  File "/home/user/.local/lib/python3.8/site-packages/vispy/app/backends/_glfw.py", line 394, in _on_resize
    self._vispy_canvas.events.resize(
  File "/home/user/.local/lib/python3.8/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/user/.local/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/home/user/.local/lib/python3.8/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/user/.local/lib/python3.8/site-packages/p5/sketch/base.py", line 157, in on_resize
    p5.renderer.reset_view()
  File "/home/user/.local/lib/python3.8/site-packages/p5/sketch/renderer2d.py", line 82, in reset_view
    self.texture_prog['modelview'] = self.modelview_matrix.T.flatten()
TypeError: 'NoneType' object does not support item assignment
ERROR: Invoking <bound method Sketch.on_resize of <Sketch (Glfw) at 0x7f1eabc1c220>> for ResizeEvent
```

**To Reproduce**
Example code executed:
```
from p5 import *

def setup():
    size(640, 360)
    no_stroke()
    background(204)

def draw():
    if mouse_is_pressed:
        fill(random_uniform(255), random_uniform(127), random_uniform(51), 127)
    else:
        fill(255, 15)

    circle_size = random_uniform(low=10, high=80)

    circle((mouse_x, mouse_y), circle_size)

def key_pressed(event):
    background(204)

run()
```

**System information:**
 - p5 version: 0.7.1
 - Python version: 3.8.10
 - Operating system: Ubuntu 20.04

**Comment by tushar5526** [comment]
Same to #340 

This was fixed and we will have it in our next release, please install p5 directly from the repository.
