### ISSUE TITLE
Error running only with renderer as Skia

### ISSUE THREAD

**Issue by mahdi-b** [p5py/p5#408]
My installation works fine with `vispy` but fails wih `Skia`.
```
Traceback (most recent call last):
  File "test.py", line 96, in <module>
    run(renderer="skia")
  File "/Users/mahdi/.local/lib/python3.8/site-packages/p5/sketch/userspace.py", line 231, in run
    p5.sketch.start()
  File "/Users/mahdi/.local/lib/python3.8/site-packages/p5/sketch/Skia2DRenderer/base.py", line 156, in start
    self.window = self.glfw_window()
  File "/Users/mahdi/.local/lib/python3.8/site-packages/p5/sketch/Skia2DRenderer/base.py", line 76, in glfw_window
    if not glfw.init():
  File "/Users/mahdi/.local/lib/python3.8/site-packages/glfw/__init__.py", line 714, in init
    res = _glfw.glfwInit()
  File "/Users/mahdi/.local/lib/python3.8/site-packages/glfw/__init__.py", line 616, in errcheck
    _reraise(exc[1], exc[2])
  File "/Users/mahdi/.local/lib/python3.8/site-packages/glfw/__init__.py", line 52, in _reraise
    raise exception.with_traceback(traceback)
  File "/Users/mahdi/.local/lib/python3.8/site-packages/glfw/__init__.py", line 595, in callback_wrapper
    return func(*args, **kwargs)
  File "/Users/mahdi/.local/lib/python3.8/site-packages/glfw/__init__.py", line 808, in _handle_glfw_errors
    raise GLFWError(message)
glfw.GLFWError: (65544) b'Cocoa: Failed to find service port for display'
```
Not sure where to start troubleshooting this. Any suggestions would be greatly appreciated

**Comment by tushar5526** [comment]
Can you share more details about your environment?

**Comment by tushar5526** [comment]
Closing this issue due to inactivity.
