### ISSUE TITLE
matmul operator on Python version <= 3.4 (rel: #18)

### ISSUE THREAD

**Issue by max0410** [p5py/p5#41]
**Test script:**

```python
from p5 import *

def setup():
    size(640, 360)
    no_stroke()
    background(204)

def draw():
    if mouse_is_pressed:
        fill(random_uniform(255), random_uniform(127), random_uniform(51), 127)
    else:
        fill(255, 15)

    circle_size = random_uniform(low=10, high=80)

    circle((mouse_x, mouse_y), circle_size)

def key_pressed(event):
    background(204)

run()


```

**Expected behavior:**
The video in the README

**Actual behavior**
An error is thrown.

**Errors produced (if any):**
```
Traceback (most recent call last):
  File "C:/Users/User/Dropbox/Programs/p5play.py", line 1, in <module>
    from p5 import *
  File "C:\Python34\lib\site-packages\p5\__init__.py", line 19, in <module>
    from .sketch import *
  File "C:\Python34\lib\site-packages\p5\sketch\__init__.py", line 19, in <module>
    from .base import *
  File "C:\Python34\lib\site-packages\p5\sketch\base.py", line 29, in <module>
    from ..opengl import renderer
  File "C:\Python34\lib\site-packages\p5\opengl\__init__.py", line 19, in <module>
    from .renderer import *
  File "C:\Python34\lib\site-packages\p5\opengl\renderer.py", line 33, in <module>
    from ..pmath import matrix
  File "C:\Python34\lib\site-packages\p5\pmath\__init__.py", line 20, in <module>
    from .vector import *
  File "C:\Python34\lib\site-packages\p5\pmath\vector.py", line 321
    return np.arccos( (self @ other) / (self.magnitude * other.magnitude))
                            ^
SyntaxError: invalid syntax
```

**p5 version:**
Newest version

**Python version:**
Python 3.4.0

**Operating System:** 
Windows 10

**Comment by abhikpal** [comment]
Hey, this seems to be related to #18. Can you try running your code on a newer version of Python (say, 3.6)?

**Comment by AliabbasMerchant** [comment]
The syntax of using '@' for matrix multiplication was introduced in Python 3.5.  
Also, this problem also includes issues due to tuple unpacking, which was introduced after Python 3.4.

As abhikpal pointed out, the script will run properly in newer versions of Python.

Maybe we will have to include Python 3.5 in the dependencies of p5py.
