### ISSUE TITLE
ModuleNotFoundError: No module named 'npy_tempita' when installing P5. 

### ISSUE THREAD

**Issue by ed-andre** [p5py/p5#465]
**Describe the bug**
I'm unable to install P5 in a portable python environment. I keep getting the following error:

```
Collecting numpy==1.18.5 (from p5)
  Using cached numpy-1.18.5.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Processing numpy/random\_bounded_integers.pxd.in
      Traceback (most recent call last):
        File "C:\Users\edmax\AppData\Local\Temp\pip-install-hpl0l8ji\numpy_2ac552a973624545af157433a22356b5\tools\cythonize.py", line 238, in <module>
          main()
        File "C:\Users\edmax\AppData\Local\Temp\pip-install-hpl0l8ji\numpy_2ac552a973624545af157433a22356b5\tools\cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "C:\Users\edmax\AppData\Local\Temp\pip-install-hpl0l8ji\numpy_2ac552a973624545af157433a22356b5\tools\cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "C:\Users\edmax\AppData\Local\Temp\pip-install-hpl0l8ji\numpy_2ac552a973624545af157433a22356b5\tools\cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "C:\Users\edmax\AppData\Local\Temp\pip-install-hpl0l8ji\numpy_2ac552a973624545af157433a22356b5\tools\cythonize.py", line 120, in process_tempita_pxd
          import npy_tempita as tempita
      ModuleNotFoundError: No module named 'npy_tempita'
      Cythonizing sources
      Traceback (most recent call last):
        File "B:\_SD\DEV\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "B:\_SD\DEV\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "B:\_SD\DEV\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "B:\_SD\DEV\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "B:\_SD\DEV\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "B:\_SD\DEV\App\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

```

**System information:**
 - Using latest P5 release
 - Python version: Python 3.11.6
 - Operating system: Windows 11

I installed Tempita successfully as a module on its own. That didn't help. Any assistance would be appreciated.

**Comment by tushar5526** [comment]
Can you try with 3.10 and check if the issue persists ?

**Comment by ed-andre** [comment]
I was able to install the P5 package on a virtual environment instead for my project. So, all is fine now.
