### ISSUE TITLE
#49 breaks the documentation auto generation

### ISSUE THREAD

**Issue by abhikpal** [p5py/p5#50]
#49 was recently merged into ```develop```. It does fix the very critical retina issue on mac, but it breaks the documentation auto-generation.

Running 
```bash
$ make html
```
inside the docs folder produces a traceback with:
```
Running Sphinx v1.6.6

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File ".../lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 59, in <module>
    import p5
  File ".../p5/__init__.py", line 19, in <module>
    from .sketch import *
  File ".../p5/sketch/__init__.py", line 19, in <module>
    from .base import *
  File ".../p5/sketch/base.py", line 59, in <module>
    actual_width, actual_height = window.get_viewport_size()
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by Manindra29** [comment]
@abhikpal  The build succeeded for me with 1 warning. Here's the build output I got:
````
(my_env) ➜  docs git:(fix-50-doc-autogen) make html
Running Sphinx v1.7.5
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: 15 added, 0 changed, 0 removed
reading sources... [100%] tutorials/index
WARNING: autodoc: failed to import function 'pow' from module 'p5'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/mmoharana/workspace/pyenvs/my_env/lib/python3.6/site-packages/sphinx/util/inspect.py", line 204, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'p5' has no attribute 'pow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mmoharana/workspace/pyenvs/my_env/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 176, in import_object
    obj = attrgetter(obj, attrname)
  File "/Users/mmoharana/workspace/pyenvs/my_env/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 274, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Users/mmoharana/workspace/pyenvs/my_env/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1517, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Users/mmoharana/workspace/pyenvs/my_env/lib/python3.6/site-packages/sphinx/util/inspect.py", line 220, in safe_getattr
    raise AttributeError(name)
AttributeError: pow

<string>:docstring of builtins.max:1: WARNING: Inline emphasis start-string without end-string.
<string>:docstring of builtins.max:1: WARNING: Inline emphasis start-string without end-string.
<string>:docstring of builtins.min:1: WARNING: Inline emphasis start-string without end-string.
<string>:docstring of builtins.min:1: WARNING: Inline emphasis start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] tutorials/index
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 5 warnings.

The HTML pages are in _build/html.
````
