### ISSUE TITLE
Trouble installing GLFW on windows

### ISSUE THREAD

**Issue by andrey-gvrd** [p5py/p5#54]
I've downloaded GLFW as [instructed](http://p5.readthedocs.io/en/latest/install.html#prerequisites-glfw).

I've tried:

- Putting the location of the DLL it into PATH
- Putting DLL itself into `SysWOW64`
- Putting DLL itself into `Python36-32\Lib\site-packages\p5`

Nothing works, same error.

**Test script:**

```python
from p5 import *
```

**Errors produced (if any):**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\p5\__init__.py", line 19, in <module>
    from .sketch import *
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\p5\sketch\__init__.py", line 19, in <module>
    vispy.use('glfw')
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vispy\util\wrappers.py", line 96, in use
    use_app(app)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vispy\app\application.py", line 49, in __init__
    self._use(backend_name)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vispy\app\application.py", line 223, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Glfw":
[WinError 193] %1 is not a valid Win32 application
```

**p5 version:**

0.4.0a1

**Python version:**

Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32

**Operating System:** 

Windows 10 x64

**Comment by abhikpal** [comment]
Hmm. I don't have access to a windows machine so, can't verify it at the moment. @Manindra29, could you see if there's some step missing?

**Comment by Manindra29** [comment]
@andrey-gvrd - Here's what I added to my Windows PATH: ```C:\Users\Manindra\Downloads\glfw-3.2.1.bin.WIN64\lib-mingw-w64```

**Comment by avdotion** [comment]
@andrey-gvrd,
Unfortunately, I had the same issue.
I've just downloaded **32-bit package** instead of 64-bit. Now everything works fine!

Windows PATH (32-bit):
`C:\Program Files\GLFW\lib-mingw`.

**Comment by wildanpurnomo** [comment]
How was the solution? I encounter the same problem. I have downloaded the right one (GLFW 64-bit Windows Binary)

**Comment by dbhavsar76** [comment]
Hi, check out issue #76 , i have a detailed answer on this problem.
Thanks.

**Comment by mberoakoko** [comment]
> Hi, check out issue #76 , i have a detailed answer on this problem.
> Thanks.

It doesn't work , tried everything , but it is broken

**Comment by MrPancakes39** [comment]
> @andrey-gvrd,
> Unfortunately, I had the same issue.
> I've just downloaded **32-bit package** instead of 64-bit. Now everything works fine!
> 
> Windows PATH (32-bit):
> `C:\Program Files\GLFW\lib-mingw`.

It look like this problem is still present but this worked for me...
