### ISSUE TITLE
Error due to calling show() on uninitialized default_sketch.

### ISSUE THREAD

**Issue by jessopb** [p5py/p5#64]
**Test script:**

```python
# put your test script here
from p5 import *
exit()
```

**Expected behavior:**
Should actually exit.

**Actual behavior**
Does not exit()

**Errors produced (if any):**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jessop/git/vendor/p5/p5/sketch/userspace.py", line 213,
in exit
    default_sketch.show(visible=False)
AttributeError: 'NoneType' object has no attribute 'show'
```
**p5 version:**
'0.4.0a1.dev2' from git 6d82eb85a160d1c5d36b6ef443b7b9e9d3f1e2cf

**Python version:**
3.6.5
**Operating System:** 
Manjaro

**Comment by abhikpal** [comment]
Thanks for bringing this up! I just pushed a fix on the `develop` branch.
