### ISSUE TITLE
Can't get load_pixels to work on the windows P5 platform

### ISSUE THREAD

**Issue by afaber999** [p5py/p5#72]
Try to use load pixels, not sure if I use the right syntax since I couldn't find an example using the load_pixel function

Using the following sketch

```python
from p5 import *

img = load_image('./test_image.jpg')

def setup():
     size(1024, 512)


def draw():
     background(0)
     with img.load_pixels():
          pass
     #image(img, (0, 0))
     

if __name__ == '__main__':
    run()
```

**Expected behavior**
To show the image and be able to access the pixels, but get the following error dump

```python
WARNING: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python3\lib\idlelib\run.py", line 144, in main
    ret = method(*args, **kwargs)
  File "C:\python3\lib\idlelib\run.py", line 474, in runcode
    exec(code, self.locals)
  File "C:\Projects\p5\load_pixel_test\load_pixel_test.py", line 17, in <module>
    run()
  File "C:\python3\lib\site-packages\p5-0.5.0-py3.6.egg\p5\sketch\userspace.py", line 146, in run
    app.run()
  File "C:\python3\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\python3\lib\site-packages\vispy\app\application.py", line 142, in run
    return self._backend._vispy_run()
  File "C:\python3\lib\site-packages\vispy\app\backends\_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "C:\python3\lib\site-packages\vispy\app\backends\_glfw.py", line 183, in _vispy_process_events
    timer._tick()
  File "C:\python3\lib\site-packages\vispy\app\backends\_glfw.py", line 516, in _tick
    self._vispy_timer._timeout()
  File "C:\python3\lib\site-packages\vispy\app\timer.py", line 168, in _timeout
    count=self.iter_count)
  File "C:\python3\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\python3\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\python3\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\python3\lib\site-packages\p5-0.5.0-py3.6.egg\p5\sketch\base.py", line 150, in on_timer
    self.draw_method()
  File "C:\Projects\p5\load_pixel_test\load_pixel_test.py", line 11, in draw
    with img.load_pixels():
AttributeError: __enter__
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x20ac41339e8>> for Event
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x20ac41339e8>> repeat 2
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x20ac41339e8>> repeat 4
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x20ac41339e8>> repeat 8
ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x20ac41339e8>> repeat 16
Traceback (most recent call last):
  File "C:\Projects\p5\load_pixel_test\load_pixel_test.py", line 17, in <module>
    run()
  File "C:\python3\lib\site-packages\p5-0.5.0-py3.6.egg\p5\sketch\userspace.py", line 146, in run
    app.run()
  File "C:\python3\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\python3\lib\site-packages\vispy\app\application.py", line 142, in run
    return self._backend._vispy_run()
  File "C:\python3\lib\site-packages\vispy\app\backends\_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "C:\python3\lib\site-packages\vispy\app\backends\_glfw.py", line 181, in _vispy_process_events
    glfw.glfwPollEvents()
```

**System information:**
 - P5 0.50
 - Python 3.6.6:
 - Windows 10:

**Additional context**
No sure if I use the right syntax, since I'm not very familiar with Python

**Comment by abhikpal** [comment]
You don't need that call to load pixels. Take a look at [this](https://github.com/p5py/p5-examples/blob/master/reference/image/pimage/pimage.py) example to see how to display an image. 

In p5, you don't need `load_pixels` to work with images as the loading / updating is done automatically. 
The function is only there if you want to force a reload of the image data (see [this](https://p5.readthedocs.io/en/latest/reference/image.html#p5.PImage.load_pixels)). However, in that case, you wouldn't use it with the `with` keyword. You only need explicit `load_pixels` calls if you want to edit the pixels of the sketch itself (refer to the documentation [here](https://p5.readthedocs.io/en/latest/reference/image.html#p5.load_pixels)).

I'm closing this issue here, but if you think it's helpful to have an example on `img.load_pixels` please open an issue on the [examples repository.](https://github.com/p5py/p5-examples/issues)

**Comment by afaber999** [comment]
Hi I want to change the pixels, but according the documentation I need to the use the with load_pixels(): construct in order to access the pixels. However, as soon as I use this with load_pixels() construct I get an error. as indicated by the submission of this issue. So the question remains if this is a P5 issue or do I use the wrong construct to access/modify the image pixels
