### ISSUE TITLE
RuntimeError: Could not create window

### ISSUE THREAD

**Issue by asaph96** [p5py/p5#93]
I'm trying to run the first example from the documentation, but I'm getting this RuntimeError

```
(game) C:\Users\LuizFernando>python Desktop\run.py
Traceback (most recent call last):
  File "Desktop\run.py", line 10, in <module>
    run()
  File "C:\Users\LuizFernando\Anaconda3\envs\game\lib\site-packages\p5\sketch\userspace.py", line 136, in run
    default_sketch = Sketch(setup_method, draw_method, handlers, frame_rate)
  File "C:\Users\LuizFernando\Anaconda3\envs\game\lib\site-packages\p5\sketch\base.py", line 112, in __init__
    resizable=False,
  File "C:\Users\LuizFernando\Anaconda3\envs\game\lib\site-packages\vispy\app\canvas.py", line 205, in __init__
    self.create_native()
  File "C:\Users\LuizFernando\Anaconda3\envs\game\lib\site-packages\vispy\app\canvas.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "C:\Users\LuizFernando\Anaconda3\envs\game\lib\site-packages\vispy\app\backends\_glfw.py", line 275, in __init__
    raise RuntimeError('Could not create window')
RuntimeError: Could not create window
```

The file "run.py" that I'm running contains this:

```
from p5 import *

def draw():
    background(255)
    stroke(0)
    fill(150)
    rect((50, 50), 75, 100)

if __name__ == '__main__':
    run()
```

I'm running in a Windows10, python=3.6.8, p5=0.5.0, vispy=0.5.3

**Comment by auraz** [comment]
A quick search shows that it could be glfw issues. Issues could be: a) open gl version is less than 4.1 b) you are using windows remote https://stackoverflow.com/questions/53211062/glfwerror-failed-to-create-glfw-window-windows c) something else.
So it may not be p5 issue, and may be. Are you able to run vispy standalone?

**Comment by vaishnavsm** [comment]
This is almost definitely an OpenGL or GLFW issue. Going through your stack trace, the error comes from a native call to the GLFW binaries, after checking that the binaries exist. The error is thrown only when the returned window pointer is null. Most probably, your OpenGL version is too low. Maybe try updating your drivers?

PS, if you can get it working through other modes of Processing, please do report. It could then be an issue with GLFW, which would have to be looked into.

Your code works perfectly!
